services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    networks:
      - default
  
  ollama:
    container_name: ollama
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    networks:
      - default
    deploy:                       # Comment this out if there is no gpu support
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  app:
    container_name: app
    depends_on:
      - qdrant
      - ollama
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./.cache:/root/.cache
    networks:
      - default

networks:
  default:
    driver: bridge