services:
  qdrant:
    container_name: qdrant
    build:
      context: ./qdrant
      dockerfile: Dockerfile
    ports:
      - "6333:6333"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
  
  ollama:
    container_name: ollama
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    container_name: app
    depends_on:
      qdrant:
        condition: service_healthy
      ollama:
        condition: service_started
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - default

networks:
  default:
    driver: bridge